name: jenny
type: laravel
docroot: public
php_version: "8.1"
webserver_type: nginx-fpm
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
database:
  type: "mysql"
  version: "8.0"
use_dns_when_possible: true
composer_version: "2"
web_environment: []
corepack_enable: false